# Generated by Django 3.2.5 on 2021-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjamapp', '0003_comment1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hits',
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
