# Generated by Django 3.2.5 on 2021-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjamapp', '0006_auto_20210806_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_site_name', models.CharField(max_length=30)),
                ('book_url', models.URLField()),
                ('book_contents', models.TextField(blank=True)),
                ('book_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-book_created'],
            },
        ),
    ]
