# Generated by Django 3.2.5 on 2021-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjamapp', '0007_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['book_site_name']},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='book_contents',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='book_created',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='book_site_name',
            field=models.CharField(max_length=50),
        ),
    ]
